
package prod.businessLogic.webservices.clients;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DeveloperServiceService", targetNamespace = "http://implementation.webservices.businessLogic.prod/", wsdlLocation = "http://localhost:8280/CRM_Projekt_WI14C/DeveloperServiceService?wsdl")
public class DeveloperServiceService
    extends Service
{

    private final static URL DEVELOPERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException DEVELOPERSERVICESERVICE_EXCEPTION;
    private final static QName DEVELOPERSERVICESERVICE_QNAME = new QName("http://implementation.webservices.businessLogic.prod/", "DeveloperServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8280/CRM_Projekt_WI14C/DeveloperServiceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEVELOPERSERVICESERVICE_WSDL_LOCATION = url;
        DEVELOPERSERVICESERVICE_EXCEPTION = e;
    }

    public DeveloperServiceService() {
        super(__getWsdlLocation(), DEVELOPERSERVICESERVICE_QNAME);
    }

    public DeveloperServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEVELOPERSERVICESERVICE_QNAME, features);
    }

    public DeveloperServiceService(URL wsdlLocation) {
        super(wsdlLocation, DEVELOPERSERVICESERVICE_QNAME);
    }

    public DeveloperServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEVELOPERSERVICESERVICE_QNAME, features);
    }

    public DeveloperServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeveloperServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DeveloperService
     */
    @WebEndpoint(name = "DeveloperServicePort")
    public DeveloperService getDeveloperServicePort() {
        return super.getPort(new QName("http://implementation.webservices.businessLogic.prod/", "DeveloperServicePort"), DeveloperService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeveloperService
     */
    @WebEndpoint(name = "DeveloperServicePort")
    public DeveloperService getDeveloperServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://implementation.webservices.businessLogic.prod/", "DeveloperServicePort"), DeveloperService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEVELOPERSERVICESERVICE_EXCEPTION!= null) {
            throw DEVELOPERSERVICESERVICE_EXCEPTION;
        }
        return DEVELOPERSERVICESERVICE_WSDL_LOCATION;
    }

}
